### ISSUE TITLE
Remove node_modules from repo + Add .gitignore

### ISSUE THREAD

**Issue by Kyle-HeatEng** [liamquinn14/wordchain#9]
Your going to run into issues with the node_modules as you add more dependancies to your application. You should use a .gitignore and add `**/node_modules` to prevent git staging the node_modules.

https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/

**Comment by liamquinn14** [comment]
thank you. i had a gitignore in both client/server directories but now ive moved it into the root. is this sorted now?

**Comment by Kyle-HeatEng** [comment]
Nice one, you can close this ticket once you have deleted node_modules from main. Good idea to get into the workflow of creating prs and linking the issues to them. That way you can track work that has been done and you can close issues when the prs get merged to main.

**Comment by liamquinn14** [comment]
thank you. and yes ive been using branches and issues but now just need to do PRs
